name: CD - Deploy to Server

on:
  push:
    branches: [ "v1ncentt-branch" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/v1ncentt/eto-app
            git pull origin v1ncentt-branch
            cd backend
            /usr/bin/python3 -m pip install -r requirements.txt
            cd ../frontend
            npm install
            npm run build
            sudo systemctl restart eto-backend
            sudo systemctl restart nginx
